import type { Metadata } from "next";
import { Inter, Cormorant_Unicase, Martel_Sans } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "db projecto final",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-auto">
      <head>
        <link rel="icon" href="/images/favicon.ico" sizes="any" />
      </head>
      <body className={inter.className}>
        <Header />
        <div
          style={{
            minHeight: "100vh",
          }}
        >
          {children}
        </div>
      </body>
    </html>
  )
}
